;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-visual-indented-line
        clipboard-kill-ring-save
        other-window-or-split
        yas-expand
        ))
